name: Deploy to Docker Swarm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./
        push: true
        tags: digilib:latest

    - name: Deploy to Docker Swarm
      uses: wshihadeh/docker-deployment-action@v2
      with:
        remote_docker_host: localhost
        docker_username: Algorithmxxx
        docker_password: ${{ secrets.DOCKER_PASSWORD }}
        deployment_mode: docker-swarm
        stack_file_name: docker-compose.yaml
        args: your_application
        deploy_path: /home/algorithmx/my-deployment
