name: Docker Image Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build the Docker image
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap
        docker buildx build . --file Dockerfile --tag digilib:$(date +%s)

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push digilib:$(date +%s)

    - name: Deploy to Docker Swarm
      uses: wshihadeh/docker-deployment-action@v1
      with:
        docker_username: Algorithmxxx
        docker_password: Sammyone@1
        deployment_mode: docker-swarm
        copy_stack_file: true
        deploy_path: /home/algorithmx/deployment
        stack_file_name: docker-compose.yml
        keep_files: 5
        args: my_application
